### ISSUE TITLE
Include step in ReadMe to update Anchor.toml and lib.rs files with same program ID

### ISSUE THREAD

**Issue by saintjer2224** [687c/solana-nft-anchor#2]
NFT minting fails after running "anchor test" command with the following error: "Error: failed to send transaction: invalid transaction: Transaction failed to sanitize accounts offsets correctly." If project is forked, make sure to have Anchor.toml and lib.rs files updated with same Program ID (generated from anchor deploy).

[programs.devnet]
solana_nft_anchor = "<PROGRAM ID>"

declare_id!("<PROGRAM ID>");

Related issue: https://stackoverflow.com/questions/70987634/solana-anchor-error-failed-to-send-transaction-invalid-transaction-transactio

**Comment by jim4067** [comment]
done. Thanks for raising this.
